import pyautogui
import subprocess
import time

def open_notepad():
    subprocess.Popen('notepad.exe')
    time.sleep(1)  # Wait for Notepad to open

def type_text(text):
    pyautogui.write(text)

def main():
    open_notepad()
    type_text("Hello, this is text generated by Python!")

if __name__ == "__main__":
    main()